[meta]
name = "Replay Manager"
version = "0.3.0"
author = "AnythingGoes"
description = "Pause, speed (.1x to 5x), scrubbing, default / follow 3D / free cameras, camera distance, and seeing through objects."
min_host = "0.9.0"

[script]
files = ["main.as"]
timeout = 50
